version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mad-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ci9STOvqPRJYGns6EBMAbKu8pLzCW0Na
      MYSQL_DATABASE: madcms
    ports:
      - "3307:3306" # Host:Container (Avoid conflict with local 3306)
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - mad-network

  mad-backend:
    build: ./mad-backend
    container_name: mad-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/madcms?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ci9STOvqPRJYGns6EBMAbKu8pLzCW0Na
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - mad-network

  mad-frontend:
    build: ./mad-frontend
    container_name: mad-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mad-backend
    networks:
      - mad-network

volumes:
  mysql_data:


networks:
  mad-network:
    driver: bridge
